"""updating review table

Revision ID: 210c70bdbbaa
Revises: ba02cbc52802
Create Date: 2025-03-02 12:29:23.324856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '210c70bdbbaa'
down_revision: Union[str, None] = 'ba02cbc52802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'update_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
